[package]
name = "drv-stm32l0-sys"
version = "0.1.0"
edition = "2018"

[dependencies]
userlib = {path = "../../sys/userlib"}
zerocopy = "0.6.1"
num-traits = { version = "0.2.12", default-features = false }
stm32l0 ={version = "0.14", default-features = false}
idol-runtime = {git = "https://github.com/oxidecomputer/idolatry.git"}

drv-stm32l0-sys-api = {path = "../stm32l0-sys-api"}

[build-dependencies]
idol = {git = "https://github.com/oxidecomputer/idolatry.git"}

[features]
l0x3 = ["stm32l0/stm32l0x3"]

# This section is here to discourage RLS/rust-analyzer from doing test builds,
# since test builds don't work for cross compilation.
[[bin]]
name = "drv-stm32l0-sys"
test = false
bench = false
